### ISSUE TITLE
Make reveal slides easily visible for visitors

### ISSUE THREAD

**Issue by JoshOrndorff** [RChain-Collaborative-Learning/PiCalculus#1]
The link to the lesson1 reveal slides from the readme should ideally go directly to the rendered slides for convenient online viewing. This works as expected on my local system.

On github, the link, instead, goes to a listing of the HTML output from pandoc. Even clicking the "RAW" link does not render the presentation.

**Comment by Jake-Gillberg** [comment]
Might it be possible to do this with github pages? @dckc did something similar with https://github.com/dckc/togl/blob/master/picalc2.lidr to http://www.madmode.com/togl/picalc2

**Comment by dckc** [comment]
It couldn't have been easier:
  1. start at https://pages.github.com/
  2. choose "project site"
  3. choose "start from scratch"
  4. commit docs/somepage.html
  5. change repository settings (use the `docs/` option)
  6. _there is no step 6_

**Comment by Jake-Gillberg** [comment]
Followed the steps above, got part-way there: https://rchain-collaborative-learning.github.io/PiCalculus/lesson1.html

Looks like the LaTeX isn't rendering

**Comment by JoshOrndorff** [comment]
Latex looks fine to me in all of
* Firefox for android
* Firefox 52 on Debian 9
* Epiphany on Debian 9

The committed html file is rendered using MathML

Can anyone else confirm either having or not having the issue?

**Comment by Jake-Gillberg** [comment]
Hmm, yeah.

LaTeX Not Working:
 - Chromium & Chrome 65 on Debian 9

Working:
 - Firefox 59 on Debian 9

**Comment by JoshOrndorff** [comment]
I've reproduced the issue in chromium. It turns out neither chrome nor chromium support MathML as evidenced by https://developer.mozilla.org/en-US/docs/Mozilla/MathML_Project/MathML_Torture_Test

One easy solution is to use mathjax instead. That will also add support for ancient browsers. Only problem is that we'll have another dependency. I'm ready to do it if it sounds good.

**Comment by Jake-Gillberg** [comment]
Probably would be nice? But I would also be okay waiting until someone else complains :)

**Comment by JoshOrndorff** [comment]
I thought this would be a trivial change where I just switch `--mathml` to `--mathjax` in the pandoc command. But the `--mathjax` flag includes a link to a no-longer-working CDN for the mathjax library.

So I tried using a local mathjax copy by `--mathjax=MathJax/MathJax.js` according to http://pandoc.org/MANUAL.html but then the result just didn't render. The js did get included correctly.

So I'm not sure where to go next.

**Comment by dckc** [comment]
Try `--katex`? That's what I used: https://github.com/dckc/togl/blob/master/Makefile

**Comment by JoshOrndorff** [comment]
`--katex` and `--mathjax` both look like the screenshot for me. Open to suggestions.
![screenshot from 2018-05-02 23-20-57](https://user-images.githubusercontent.com/2915325/39558812-c4f7e8a4-4e5f-11e8-852d-5cc30a4ca883.png)

**Comment by dckc** [comment]
Try a newer `pandoc`? `--katex` addressed this issue for me here with chrome on Ubuntu (using pandoc from nix):

```
~/projects/PiCalculus$ rm lesson1.html && make
pandoc --standalone --katex -f markdown+smart --to revealjs --slide-level 2 --output lesson1.html lesson1.md

~/projects/PiCalculus$ pandoc --version
pandoc 2.1.2
Compiled with pandoc-types 1.17.3.1, texmath 0.10.1.1, skylighting 0.6
Default user data directory: /home/connolly/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

~/projects/PiCalculus$ ls -l `type -p pandoc`
lrwxrwxrwx 1 connolly connolly 67 Dec 31  1969 /home/connolly/.nix-profile/bin/pandoc -> /nix/store/af472qm7s8v7dyb848w17pfv3lm75skk-pandoc-2.1.2/bin/pandoc
```

**Comment by JoshOrndorff** [comment]
Indeed I just needed a newer pandoc. Should have known the debian repos would be stale.
